//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef S1010329_SOM_WXCRAFTER_BASE_CLASSES_H
#define S1010329_SOM_WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/button.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/menu.h>
#include <wx/toolbar.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class MainFrameBaseClass : public wxFrame
{
protected:
    wxPanel* m_mainPanel;
    wxButton* m_button13;
    wxButton* m_button15;
    wxStaticText* m_staticText29;
    wxTextCtrl* m_textCtrl_IterationTimes;
    wxStaticText* m_staticText_Neurons;
    wxTextCtrl* m_textCtrl_weights;
    wxButton* m_button37;
    wxMenuBar* m_menuBar;
    wxMenu* m_name6;
    wxMenuItem* m_menuItem7;
    wxMenu* m_name8;
    wxMenuItem* m_menuItem9;
    wxToolBar* m_mainToolbar;

protected:
    virtual void OnBtnSquare(wxCommandEvent& event) { event.Skip(); }
    virtual void OnUpdateSquare(wxUpdateUIEvent& event) { event.Skip(); }
    virtual void OnBtnTriangle(wxCommandEvent& event) { event.Skip(); }
    virtual void OnUpdateTriangle(wxUpdateUIEvent& event) { event.Skip(); }
    virtual void OnBtnStop(wxCommandEvent& event) { event.Skip(); }
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnAbout(wxCommandEvent& event) { event.Skip(); }

public:
    wxButton* GetButton13() { return m_button13; }
    wxButton* GetButton15() { return m_button15; }
    wxStaticText* GetStaticText29() { return m_staticText29; }
    wxTextCtrl* GetTextCtrl_IterationTimes() { return m_textCtrl_IterationTimes; }
    wxStaticText* GetStaticText_Neurons() { return m_staticText_Neurons; }
    wxTextCtrl* GetTextCtrl_weights() { return m_textCtrl_weights; }
    wxButton* GetButton37() { return m_button37; }
    wxPanel* GetMainPanel() { return m_mainPanel; }
    wxMenuBar* GetMenuBar() { return m_menuBar; }
    wxToolBar* GetMainToolbar() { return m_mainToolbar; }
    MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("My Frame"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxCAPTION|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxCLOSE_BOX);
    virtual ~MainFrameBaseClass();
};

#endif
